version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - SEPOLIA_RPC=${SEPOLIA_RPC}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - SEND_VALUE=${SEND_VALUE}
      - PORT=3001
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_SAFE_API_KEY=${VITE_SAFE_API_KEY}
      - VITE_PRIVATE_KEY=${VITE_PRIVATE_KEY}
      - VITE_FAUCET_ORG_ADDRESS=${VITE_FAUCET_ORG_ADDRESS}
      - VITE_CRC_AMOUNT=${VITE_CRC_AMOUNT}
      - VITE_TRUST_SCORE_THRESHOLD=${VITE_TRUST_SCORE_THRESHOLD}
    depends_on:
      - backend
    volumes:
      - ./app:/app
      - /app/node_modules
    restart: unless-stopped